### ISSUE TITLE
Replace favicon

### ISSUE THREAD

**Issue by ceilican** [StabilityNexus/Gluon-Solidity-WebUI#11]
This repo is currently using the default favicon from next.js. 

Let's generate a favicon for gluon from the following logos:

![GluonProtocol-Darker](https://github.com/user-attachments/assets/86ba79e3-c7a8-45e0-b678-d0bbaadec7e3)
![GluonProtocol-Darker](https://github.com/user-attachments/assets/585799a9-30cf-43b6-96d9-f39415397053)
![GluonProtocol-FlatG](https://github.com/user-attachments/assets/3807ec67-f06e-4b62-9a9f-3c0472273b09)
![GluonProtocol-FlatG](https://github.com/user-attachments/assets/577020a8-9263-435b-af32-eaba8eeadb0b)
![GluonProtocol-Lighter](https://github.com/user-attachments/assets/1e84c0f7-6bdd-4306-87e9-108f03fd6f7f)
![GluonProtocol-Lighter](https://github.com/user-attachments/assets/6f7363dd-13bb-4b38-9675-82afeccd2bbb)

**Comment by atharvarai** [comment]
> This repo is currently using the default favicon from next.js.
> 
> Let's generate a favicon for gluon from the following logos:
> 
> ![GluonProtocol-Darker](https://private-user-images.githubusercontent.com/1809436/393242479-86ba79e3-c7a8-45e0-b678-d0bbaadec7e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ1NDUsIm5iZiI6MTczMzUyNDI0NSwicGF0aCI6Ii8xODA5NDM2LzM5MzI0MjQ3OS04NmJhNzllMy1jN2E4LTQ1ZTAtYjY3OC1kMGJiYWFkZWM3ZTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjIzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzMyYmU2ZjQwZDI5NzBhOTZjYjdjYmRmNDA0NDY5OTRjYWI5N2ZmMGFjYTg1NmI3OWJkY2JhYzdkZTNiZGEyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ._1AyBp9T147Aiia-1nGn4N8TXDX6VTEoF2VzGAuiTGc) ![GluonProtocol-Darker](https://private-user-images.githubusercontent.com/1809436/393242487-585799a9-30cf-43b6-96d9-f39415397053.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ1NDUsIm5iZiI6MTczMzUyNDI0NSwicGF0aCI6Ii8xODA5NDM2LzM5MzI0MjQ4Ny01ODU3OTlhOS0zMGNmLTQzYjYtOTZkOS1mMzk0MTUzOTcwNTMuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjIzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTM1N2E4NzFhMGQ1NTk3MWNlYTczOGM2YWU1NWU1M2EwMzYxMDQzOWY3Y2U4MzZhMjllYzMxZGMwYzQ1ZGMxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.1F3Xd-LKM3vvdwW2ZCj1a5zsTA_uYjxxROAJokhPHYM) ![GluonProtocol-FlatG](https://private-user-images.githubusercontent.com/1809436/393242489-3807ec67-f06e-4b62-9a9f-3c0472273b09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ1NDUsIm5iZiI6MTczMzUyNDI0NSwicGF0aCI6Ii8xODA5NDM2LzM5MzI0MjQ4OS0zODA3ZWM2Ny1mMDZlLTRiNjItOWE5Zi0zYzA0NzIyNzNiMDkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjIzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTg0NjkxNzQyODJlNjM2YmJhNjc2YTFiZWI3OTliOTU1ZTlhZTEzMzc2ZjE1MzBjZGE5N2NmYWZiNzRlNjQ1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.IvupIfsCVdKWbpqEVw43XcTbbPoxxDQJac5AEYSMFDs) ![GluonProtocol-FlatG](https://private-user-images.githubusercontent.com/1809436/393242490-577020a8-9263-435b-af32-eaba8eeadb0b.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ1NDUsIm5iZiI6MTczMzUyNDI0NSwicGF0aCI6Ii8xODA5NDM2LzM5MzI0MjQ5MC01NzcwMjBhOC05MjYzLTQzNWItYWYzMi1lYWJhOGVlYWRiMGIuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjIzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTBkZWIyNjdkMjQxMTAyN2RlMTRmN2NiMjM2YmNhZWI1YTU5NDMzOTNmMmMzODFlYzI1ZmRiZmJmMjI4ZDdkZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.YXXoWHQWtp_0ump3r0B1afN19-1Nv8AzSi0JFnLjyPY) ![GluonProtocol-Lighter](https://private-user-images.githubusercontent.com/1809436/393242492-1e84c0f7-6bdd-4306-87e9-108f03fd6f7f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ1NDUsIm5iZiI6MTczMzUyNDI0NSwicGF0aCI6Ii8xODA5NDM2LzM5MzI0MjQ5Mi0xZTg0YzBmNy02YmRkLTQzMDYtODdlOS0xMDhmMDNmZDZmN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjIzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWU5MTc0ZWIxNjkxYTMzMzU3YmMyNWE4MGRmZDJhOWQ2YWE2NzVhY2Q3NGJlMTIzZDE1ZWVlMWJiMzFiNDI4YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.lucbs3wpC-koZX8kM8Fh1xNU5xc-SbQbhdUzOB_8V3E) ![GluonProtocol-Lighter](https://private-user-images.githubusercontent.com/1809436/393242495-6f7363dd-13bb-4b38-9675-82afeccd2bbb.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM1MjQ1NDUsIm5iZiI6MTczMzUyNDI0NSwicGF0aCI6Ii8xODA5NDM2LzM5MzI0MjQ5NS02ZjczNjNkZC0xM2JiLTRiMzgtOTY3NS04MmFmZWNjZDJiYmIuc3ZnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMDZUMjIzMDQ1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODE2NDQxZDExMGY5YjhkNzc2ZjU3NzQwY2I2NWQ0Y2YwZWYwN2Q5NWZmOTYzMGVjZWU3ODYxYTYzYzJiZjk2YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.laBM2vopU7P6nvkq2iS45MTzbXWxFwEMPDq6495e7nw)

can i take this task !?

**Comment by atharvarai** [comment]
can I take this task !?
We just want to update the favicon of the website with the above attached image right !?
